# Generated by Django 2.2.5 on 2019-09-25 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_added_location_city_code_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationstatecode',
            name='type',
        ),
    ]
