version: '3.2'

services:
  db:
    image: postgres:11.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=codeemploy
      - POSTGRES_DB=codeemploy
  redis:
    image: redis
  web:
    build: .
    command: python3 /src/manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_SECRET=${DJANGO_SECRET}
      - DB_HOST=db
    volumes:
      - .:/src
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
  celery:
    build: .
    command: celery -A code_employ worker -l info
    volumes:
      - .:/src
    depends_on:
      - db
      - redis
  celery-beat:
    build: .
    command: celery -A code_employ beat -l info
    volumes:
      - .:/src
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
