version: '3.2'

services:
  db:
    image: postgres:11.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=codeemploy
      - POSTGRES_DB=codeemploy
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python3 /src/manage.py runserver 0.0.0.0:8000'
    environment:
      - DJANGO_SECRET=${DJANGO_SECRET}
      - DB_HOST=db
    volumes:
      - .:/src
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data:
