# Generated by Django 2.2.5 on 2019-09-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_listing', '0009_added_published_date_column_to_JobListing_model')
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='published_date',
            field=models.DateTimeField(null=True),
        ),
    ]
